### ISSUE TITLE
在博德之门3中发现的问题

### ISSUE THREAD

**Issue by lzypxi** [GlossMod/Gloss-Mod-Manager-info#1]
博德之门3中有bug。wasd模组里面有个sdl2.dll。这个文件没有正确的安装到bin文件夹，而是在nativemods文件夹又建了个bin然后再把sdl2.dll放进去。

**Comment by 3DMXM** [comment]
已经在 1.11.3 版本中修复这个问题

**Comment by lzypxi** [comment]
大佬辛苦了，感谢大佬

**Comment by lzypxi** [comment]
最新情况是 确实解决了wasd模组的sdl2.dll文件的放置问题。但是native mod loader这个前置mod依然无法正确的安装，还是在native文件夹里面又创建了个bin文件夹然后再把sdl2.dll放进去。已经可以正常使用了，剩下一点点小瑕疵，感谢大佬的付出。

**Comment by 3DMXM** [comment]
用我发的这个 Native Mod Loader  https://mod.3dmgame.com/mod/201398
