### ISSUE TITLE
[建议]: MOD类型多选自定义

### ISSUE THREAD

**Issue by LuomuCNyQ** [GlossMod/Gloss-Mod-Manager-info#10]
### 建议

同一个MOD的压缩包里可能会有多个类型需要分开放到多个目录下（目前只能识别出一个并同时都放到一个目录下），希望改善一下或者多出自定义选项，手动选择每个类型需要放的位置目录（可以把一个压缩包内的不同类型能正确的放到他应该放的目录下）

**Comment by 3DMXM** [comment]
可以将不同部分的内容，单独打包为压缩包，然后再单独拖入GMM里面，以多个Mod的新式进行安装，比如说这样 
![image](https://github.com/GlossMod/Gloss-Mod-Manager-info/assets/28587093/330308cf-4ff3-4a1e-9e0c-54b1b35832ef)
