### ISSUE TITLE
[求助]: 是xpg的生化危机3重置版使用mod启动游戏会崩溃

### ISSUE THREAD

**Issue by shangjigao** [GlossMod/Gloss-Mod-Manager-info#11]
### 是否已读文档

- [X] 已读

### 游戏

生化危机3重置版

### Mod地址

用任何mod都会崩溃

### 问题描述

游戏是从xbox下载的生化危机3重置版，加载mod后启动游戏就会崩溃，不用mod没事儿

### 管理器版本

1.30.1

**Comment by 3DMXM** [comment]
手动换一下最新的 REFramework 框架试试  https://github.com/praydog/REFramework/releases

下 [RE3_TDB67.zip](https://github.com/praydog/REFramework/releases/download/v1.5.3/RE3_TDB67.zip)
