### ISSUE TITLE
[建议]: 龙之信条2 部分lua脚本附带的文件安装不完全

### ISSUE THREAD

**Issue by niyuyeye** [GlossMod/Gloss-Mod-Manager-info#13]
### 建议

龙之信条2 部分lua脚本在autorun文件夹的同级文件夹也有文件，比如Damage Number，Higher Item Stack Number，Advanced Clock Widget，这些mod的data文件夹和fonts文件夹没有被安装

**Comment by 3DMXM** [comment]
有示例Mod没，我测测

**Comment by niyuyeye** [comment]
> 有示例Mod没，我测测

[HighItemStackNumber-183-1-0-1711486144.zip](https://github.com/GlossMod/Gloss-Mod-Manager-info/files/14799437/HighItemStackNumber-183-1-0-1711486144.zip)

[DamageNumber-148-1-6-1711638456.zip](https://github.com/GlossMod/Gloss-Mod-Manager-info/files/14799441/DamageNumber-148-1-6-1711638456.zip)

**Comment by niyuyeye** [comment]
> 有示例Mod没，我测测

建议需要 reframework 的 mod，建议直接将压缩包里 reframework 文件夹内的所有文件都移动到游戏的对应位置，如果有覆盖关系的话按照排序进行覆盖

**Comment by 3DMXM** [comment]
1.36.1  版本已修复此问题， 将Mod重新添加到管理器即可

**Comment by niyuyeye** [comment]
> 1.36.1 版本已修复此问题， 将Mod重新添加到管理器即可

谢谢
