### ISSUE TITLE
【幻兽帕鲁】安装UE4SS后经常游戏崩溃

### ISSUE THREAD

**Issue by jKill** [GlossMod/Gloss-Mod-Manager-info#14]
### 管理器版本

v1.36.1

### 描述

安装了UE4SS 3.0.1和3dmmods_终端显示个体值MODv0 。玩帕鲁经常会游戏崩溃，有时候是玩一会崩，有时刚打开就崩。。。。

### 如何触发

安装UE4SS 3.0.1和3dmmods_终端显示个体值MODv0 。然后玩帕鲁，在终端里查看个体值

### 操作系统

Windows 11

**Comment by 3DMXM** [comment]
这一般是Mod的问题，你把这个问题反馈给Mod作者去，
