### ISSUE TITLE
[Bug]: 游戏为打开显示游戏正在运行

### ISSUE THREAD

**Issue by kakaaaaa4** [GlossMod/Gloss-Mod-Manager-info#15]
### 描述

A bug happened!
七日杀未打开，GMM显示游戏正在运行中

### 如何触发

A bug happened!

### 操作系统

Windows 11

**Comment by 3DMXM** [comment]
`win+R`输入`cmd`, 然后在控制台输入 `tasklist | findstr 7DaysToDie.exe` 看是否有内容输出.

如果你想在游戏运行中安装/卸载 Mod，可以在设置里面启用`游戏运行时修改` 这个选项

**Comment by kakaaaaa4** [comment]
C:\Windows\System32>tasklist | findstr 7DaysToDie.exe
7DaysToDie.exe               11072                           16         32 K

C:\Windows\System32>taskkill /pid 11072
错误: 无法终止 PID 为 11072 的进程。
原因: 只能强行终止这个进程(带 /F 选项)。

C:\Windows\System32>taskkill /pid 11072 -f
错误: 无法终止 PID 为 11072 的进程。
原因: 拒绝访问。

管理员权限打开仍无法杀死相关进程，请问该如何解决？

**Comment by 3DMXM** [comment]
steam也显示游戏正在运行？

**Comment by kakaaaaa4** [comment]
steam正常，游戏也可以正常运行。

**Comment by 3DMXM** [comment]
那就直接在设置里面启用 "游戏运行时修改 " 这个选项，然后无视那个提示吧

**Comment by kakaaaaa4** [comment]
后续： 正常关机、重启错误进程均存在
已解决：windows系统更新后错误进程消失，GMM恢复正常
可能的复现方法：7DaysToDie mod  冲突报红字后任务管理器强制关闭游戏

**Comment by kakaaaaa4** [comment]
复现成功：mod 冲突报红字后任务管理器强制关闭游戏会残留错误进程
