### ISSUE TITLE
[Bug]: 启动GMM，无法自动识别语音，无法报错设置，无法选择游戏

### ISSUE THREAD

**Issue by WindyGrin** [GlossMod/Gloss-Mod-Manager-info#16]
### 管理器版本

1.43.1

### 描述

启动GMM，无法自动识别语音，无法报错设置，无法选择游戏。
如果使用控制台启动GMM，报如下告警：
(node:14080) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(Use `Gloss Mod Manager --trace-deprecation ...` to show where the warning was created)
12:12:41.063 > Update for version 1.43.1 is not available (latest version: 1.43.1, downgrade is disallowed).

可能是我的Nodejs版本过高？

### 如何触发

安装后启动就会有问题。

### 操作系统

Windows 10

**Comment by 3DMXM** [comment]
这个提示是警告，不是错误，问题不在这，完整控制台输出截图看看

**Comment by WindyGrin** [comment]
![Uploading 截图.png…]()

**Comment by WindyGrin** [comment]
![截图](https://github.com/GlossMod/Gloss-Mod-Manager-info/assets/22931389/8f425566-1ff9-477f-9921-da169afea829)

**Comment by WindyGrin** [comment]
![截图2](https://github.com/GlossMod/Gloss-Mod-Manager-info/assets/22931389/a60d11b8-d30a-47a7-a05c-62bb57c067c1)

**Comment by WindyGrin** [comment]
![截图3](https://github.com/GlossMod/Gloss-Mod-Manager-info/assets/22931389/a61250b0-305b-41e0-bab4-d6824bc04807)

**Comment by WindyGrin** [comment]
看起来是证书解析的错误，要消除证书错误，您需要通过 --ignore-certificate-errors的实例添加参数 Options
https://www.soinside.com/question/yyoL4yyujanq9SwuW5Q2iQ

**Comment by WindyGrin** [comment]
看起来也不是证书的问题，证书的问题只有在我点了“About”才会报。我的其他操作控制台什么都不显示。。。。

**Comment by 3DMXM** [comment]
在 GMM 安装目录新建一个叫 DEV 的文件 ，然后重启软件，看看 console 里面的内容

**Comment by 3DMXM** [comment]
我看着感觉是权限问题，用管理员身份运行试试？

**Comment by WindyGrin** [comment]
![截图4](https://github.com/GlossMod/Gloss-Mod-Manager-info/assets/22931389/538dd223-66bc-4633-ac36-fea25b7ddf41)
我用了管理员身份运行。看起来是缺少我的文档下面的配置，没有自动创建出来，

**Comment by 3DMXM** [comment]
你有修改过 “我的文档” 的位置吗？

**Comment by WindyGrin** [comment]
没有修改过，我依照这报错在“我的文档”里面创建了对应的路径和文件，然后就开始报其他“我的文档”文件Error: ENOENT: no such file or directory。比如我在“我的文档”下面创建了“Gloss Mod Manager”，又在“Gloss Mod Manager”下面创建了“Expands”和“gmm.cache”，现在就开始报这个图里的问题了。
我在Q群里，要不Q群里共享一个我的文档下面的基础配置文件出来，我直接粘贴过去。
![截图5](https://github.com/GlossMod/Gloss-Mod-Manager-info/assets/22931389/2cec417c-8a33-4f8b-a841-4bba9e019d81)

**Comment by 3DMXM** [comment]
还有个解决方法，将 GMM 安装目录改到 C盘，

**Comment by WindyGrin** [comment]
这个办法之前也试过了，用默认安装路径到C:\Program Files，我再试一下吧

**Comment by WindyGrin** [comment]
![截图6](https://github.com/GlossMod/Gloss-Mod-Manager-info/assets/22931389/5da189f4-073a-4b79-9ce7-c197f93d3775)
确实还不行，我也想不不明白，我电脑里“我的文档”下面有一堆游戏的文档和配置，感觉不是这个目录的问题

**Comment by 3DMXM** [comment]
那你加我Q ， 我远程瞅一眼

**Comment by WindyGrin** [comment]
![88711bf1fbe5d48facbfd210932ff0f3](https://github.com/GlossMod/Gloss-Mod-Manager-info/assets/22931389/3dffc324-9fe3-4dcf-a359-8745fe5b114f)
通过在Windows defender中的“文件夹限制访问”中添加允许的应用Gloss Mod Manager.exe，可以解决
