### ISSUE TITLE
[Bug]: 游览页的筛选项【游戏类型】候选项重复显示

### ISSUE THREAD

**Issue by chenqs000** [GlossMod/Gloss-Mod-Manager-info#17]
### 管理器版本

1.48.2

### 描述

打开游览页后切换到别的页面再重新打开游览页，候选项会新增一份。
![image](https://github.com/user-attachments/assets/e4e53f67-1219-4300-a498-09eb67b2c93d)
![image](https://github.com/user-attachments/assets/b4195bd5-d97e-45c5-9681-d32ad3dcd2c9)

### 如何触发

1、首次打开游览页，此时【游戏类型】的候选项正常。
2、切换页面，比如mod详情页或者左侧导航栏的其他页面。
3、重新进入游览页，此时【游戏类型】的候选项多了一份。
我测试过，每做一次上述步骤，选项都会在之前基础上新增一份。

### 操作系统

Windows 10

**Comment by 3DMXM** [comment]
感谢反馈，将在下一个版本更新时修复

**Comment by 3DMXM** [comment]
已经在 [1.48.3](https://github.com/GlossMod/Gloss-Mod-Manager-info/releases) 版本修复此问题
