### ISSUE TITLE
[建议]: 移动存储位置的时候，能不能把设置文件一起移动了？

### ISSUE THREAD

**Issue by noneSycamore** [GlossMod/Gloss-Mod-Manager-info#4]
### 建议

主要是移动mods文件夹的时候，C盘这个文件夹下还有config.json和其他一些文件留在那里，强迫症很难受。

如果我连着config.json一起移动的话，程序不会识别出config.json在哪里，刷新之后会重新生成一个默认文件。

能不能把这个也改一下？如果哪里有问题的话请告知，我也有兴趣帮忙

PS：移动之后遇到报错：
写入文件失败：Error: EPERM: operation not permitted, open 'D:\Program Files\GlossMod Manager\mods\Cyberpunk 2077\mod.json'

**Comment by 3DMXM** [comment]
把config.json文件挪走了，程序应该上哪去找你的配置呢

**Comment by 3DMXM** [comment]
另外，磁盘根目录下的 Program Files 和 Program Files (x86) 文件夹是需要管理员权限才能读写的，不建议将储存目录丢这里面去

**Comment by noneSycamore** [comment]
> 另外，磁盘根目录下的 Program Files 和 Program Files （x86） 文件夹是需要管理员权限才能读写的，不建议将储存目录丢这里面去

谢谢，这个问题解决了
