### ISSUE TITLE
[建议]: 建议添加一个备份存档的功能

### ISSUE THREAD

**Issue by chenguoyu96** [GlossMod/Gloss-Mod-Manager-info#6]
### 建议

玩mod的时候，有时候会把存档搞坏，手动备份又太麻烦，是否考虑添加一个备份存档功能

**Comment by 3DMXM** [comment]
后续可能会考虑制作这个功能，在这之前，你可以用这个进行备份存档： https://www.nexusmods.com/site/mods/768

**Comment by 3DMXM** [comment]
[v1.44.0](https://github.com/GlossMod/Gloss-Mod-Manager-info/releases/tag/v1.44.0) 版本 已添加 备份存档的功能
