### ISSUE TITLE
[Bug]: 配置文件写死在C盘下，建议修改为和软件安装目录一致的位置

### ISSUE THREAD

**Issue by lijialong1313** [GlossMod/Gloss-Mod-Manager-info#7]
### 管理器版本

v1.30.1

### 描述

我的“我的文档”目录压根不在C盘，但是软件硬是要在C盘User文件夹用户名文件夹里创建配置文件。

你如果要放配置文件，那可以放到例如%appdata%下，并不需要放到写死路径的“我的文档”中，毕竟这都是浏览器base的软件了，chromium也一样把配置放这里。

### 如何触发

移动了

### 操作系统

Windows 11

**Comment by 3DMXM** [comment]
配置文件不能和软件安装目录丢一起，软件在更新的时候会清空安装目录，

至于丢 appdata 里面去，也有想改过去，但这回导致旧版本更新到新版本后会导致配置丢失的问题
