### ISSUE TITLE
[建议]: 想要个MOD多选功能

### ISSUE THREAD

**Issue by DeathPayner** [GlossMod/Gloss-Mod-Manager-info#8]
### 建议

可以出个MOD多选功能，MOD一多打开，删除，关闭都很麻烦，不好调试

**Comment by 3DMXM** [comment]
手动换一下最新的 REFramework 框架试试  https://github.com/praydog/REFramework/releases

下 [RE3_TDB67.zip](https://github.com/praydog/REFramework/releases/download/v1.5.3/RE3_TDB67.zip)

**Comment by 3DMXM** [comment]
1.31.0 版本已经添加此功能
